In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [2]:
pd.set_option("display.max_columns",999)

## Exploring the 3 datasets

In [3]:
df18=pd.read_parquet("../parquet_datasets/proyecciones_poblacion_departamental_2018-2050.parquet")
df18=df18[df18.AÑO==2018]
df18

,DP,DPNOM,AÑO,ÁREA GEOGRÁFICA,Hombres_0,Hombres_1,Hombres_2,Hombres_3,Hombres_4,Hombres_5,Hombres_6,Hombres_7,Hombres_8,Hombres_9,Hombres_10,Hombres_11,Hombres_12,Hombres_13,Hombres_14,Hombres_15,Hombres_16,Hombres_17,Hombres_18,Hombres_19,Hombres_20,Hombres_21,Hombres_22,Hombres_23,Hombres_24,Hombres_25,Hombres_26,Hombres_27,Hombres_28,Hombres_29,Hombres_30,Hombres_31,Hombres_32,Hombres_33,Hombres_34,Hombres_35,Hombres_36,Hombres_37,Hombres_38,Hombres_39,Hombres_40,Hombres_41,Hombres_42,Hombres_43,Hombres_44,Hombres_45,Hombres_46,Hombres_47,Hombres_48,Hombres_49,Hombres_50,Hombres_51,Hombres_52,Hombres_53,Hombres_54,Hombres_55,Hombres_56,Hombres_57,Hombres_58,Hombres_59,Hombres_60,Hombres_61,Hombres_62,Hombres_63,Hombres_64,Hombres_65,Hombres_66,Hombres_67,Hombres_68,Hombres_69,Hombres_70,Hombres_71,Hombres_72,Hombres_73,Hombres_74,Hombres_75,Hombres_76,Hombres_77,Hombres_78,Hombres_79,Hombres_80,Hombres_81,Hombres_82,Hombres_83,Hombres_84,Hombres_85,Hombres_86,Hombres_87,Hombres_88,Hombres_89,Hombres_90,Hombres_91,Hombres_92,Hombres_93,Hombres_94,Hombres_95,Hombres_96,Hombres_97,Hombres_98,Hombres_99,Hombres_100 y más,Mujeres_0,Mujeres_1,Mujeres_2,Mujeres_3,Mujeres_4,Mujeres_5,Mujeres_6,Mujeres_7,Mujeres_8,Mujeres_9,Mujeres_10,Mujeres_11,Mujeres_12,Mujeres_13,Mujeres_14,Mujeres_15,Mujeres_16,Mujeres_17,Mujeres_18,Mujeres_19,Mujeres_20,Mujeres_21,Mujeres_22,Mujeres_23,Mujeres_24,Mujeres_25,Mujeres_26,Mujeres_27,Mujeres_28,Mujeres_29,Mujeres_30,Mujeres_31,Mujeres_32,Mujeres_33,Mujeres_34,Mujeres_35,Mujeres_36,Mujeres_37,Mujeres_38,Mujeres_39,Mujeres_40,Mujeres_41,Mujeres_42,Mujeres_43,Mujeres_44,Mujeres_45,Mujeres_46,Mujeres_47,Mujeres_48,Mujeres_49,Mujeres_50,Mujeres_51,Mujeres_52,Mujeres_53,Mujeres_54,Mujeres_55,Mujeres_56,Mujeres_57,Mujeres_58,Mujeres_59,Mujeres_60,Mujeres_61,Mujeres_62,Mujeres_63,Mujeres_64,Mujeres_65,Mujeres_66,Mujeres_67,Mujeres_68,Mujeres_69,Mujeres_70,Mujeres_71,Mujeres_72,Mujeres_73,Mujeres_74,Mujeres_75,Mujeres_76,Mujeres_77,Mujeres_78,Mujeres_79,Mujeres_80,Mujeres_81,Mujeres_82,Mujeres_83,Mujeres_84,Mujeres_85,Mujeres_86,Mujeres_87,Mujeres_88,Mujeres_89,Mujeres_90,Mujeres_91,Mujeres_92,Mujeres_93,Mujeres_94,Mujeres_95,Mujeres_96,Mujeres_97,Mujeres_98,Mujeres_99,Mujeres_100 y más,Total_0,Total_1,Total_2,Total_3,Total_4,Total_5,Total_6,Total_7,Total_8,Total_9,Total_10,Total_11,Total_12,Total_13,Total_14,Total_15,Total_16,Total_17,Total_18,Total_19,Total_20,Total_21,Total_22,Total_23,Total_24,Total_25,Total_26,Total_27,Total_28,Total_29,Total_30,Total_31,Total_32,Total_33,Total_34,Total_35,Total_36,Total_37,Total_38,Total_39,Total_40,Total_41,Total_42,Total_43,Total_44,Total_45,Total_46,Total_47,Total_48,Total_49,Total_50,Total_51,Total_52,Total_53,Total_54,Total_55,Total_56,Total_57,Total_58,Total_59,Total_60,Total_61,Total_62,Total_63,Total_64,Total_65,Total_66,Total_67,Total_68,Total_69,Total_70,Total_71,Total_72,Total_73,Total_74,Total_75,Total_76,Total_77,Total_78,Total_79,Total_80,Total_81,Total_82,Total_83,Total_84,Total_85,Total_86,Total_87,Total_88,Total_89,Total_90,Total_91,Total_92,Total_93,Total_94,Total_95,Total_96,Total_97,Total_98,Total_99,Total_100 y más,Total Hombres,Total Mujeres,Total
0,5,Antioquia,2018,Cabecera Municipal,31398,31674,31916,32172,32460,32748,33071,33436,33835,34284,34803,35394,36045,36772,37569,38442,39379,40412,41629,42898,43930,44792,45319,45497,45368,45145,44827,44239,43327,42222,41122,40068,39127,38432,37841,37222,36483,35450,34022,32332,30607,28924,27599,26849,26552,26414,26428,26629,27026,27510,27945,28317,28393,28053,27409,26628,25740,24737,23751,22701,21606,20485,19381,18322,17287,16299,15326,14356,13450,12566,11695,10850,10040,9209,8413,7658,6931,6252,5624,5062,4525,4032,3585,3193,2808,2483,2184,1906,1658,1439,1250,1070,916,768,647,526,416,380,388,408,947,29904,30204,30525,30827,31176,31500,31883,32283,32732,33247,33807,34440,35145,35925,36790,37728,38757,39919,41295,42739,43968,45027,45747,46091,46078,45950,45701,45203,44422,43485,42558,41662,40977,40584,40391,40147,39806,39144,38050,36663,35243,33865,32851,32369,32322,32447,32725,33206,33886,34644,35321,35888,36116,35840,35198,34400,33405,32318,31202,30045,28798,27495,26203,24916,23655,22407,21168,19970,18811,17676,16567,15468,14393,13277,12216,11151,10145,9208,8327,7517,6776,6088,5455,4870,4354,3867,3425,3023,2673,2348,2051,1771,1540,1318,1119,930,752,695,610,695,1787,61302,61878,62441,62999,63636,64248,64954,65719,66567,67531,68610,69834,71190,72697,74359,76170,78136,80331,82924,85637,87898,89819,91066,91588,91446,91095,90528,89442,87749,85707,83680,81730,80104,79016,78232,77369,76289,74594,72072,68995,65850,62789,60450,59218,58874,58861,59153,59835,60912,62154,63266,64205,64509,63893,62607,61028,59145,57055,54953,52746,50404,47980,45584,43238,40942,38706,36494,34326,32261,30242,28262,26318,24433,22486,20629,18809,17076,15460,13951,12579,11301,10120,9040,8063,7162,6350,5609,4929,4331,3787,3301,2841,2456,2086,1766,1456,1168,1075,998,1103,2734,2351655,2621286,4972941
1,5,Antioquia,2018,Centros Poblados y Rural Disperso,14488,14314,14164,14027,13878,13742,13634,13524,13430,13351,13285,13239,13206,13198,13171,13173,13165,13087,12928,12717,12474,12192,11948,11764,11602,11423,11212,11011,10785,10555,10369,10234,10140,10080,10044,10009,9940,9820,9623,9366,9099,8836,8646,8486,8419,8387,8406,8427,8444,8438,8414,8361,8274,8162,8032,7839,7627,7386,7147,6913,6652,6405,6129,5824,5512,5195,4885,4587,4322,4082,3836,3587,3335,3089,2843,2609,2375,2171,1970,1791,1613,1458,1315,1173,1064,943,834,744,653,572,504,426,371,320,262,196,165,152,107,132,246,14045,13818,13596,13374,13179,12976,12811,12630,12489,12351,12238,12137,12067,12003,11951,11925,11887,11812,11676,11487,11305,11089,10918,10816,10749,10669,10555,10439,10283,10107,9974,9891,9827,9769,9723,9675,9593,9468,9275,9019,8754,8493,8283,8132,8054,8023,8042,8051,8016,7991,7950,7868,7768,7644,7511,7325,7107,6870,6623,6361,6090,5819,5539,5240,4946,4641,4355,4092,3840,3594,3379,3146,2916,2698,2476,2258,2051,1857,1683,1518,1374,1221,1100,975,868,777,679,600,529,462,404,348,295,250,215,164,143,121,110,144,278,28533,28132,27760,27401,27057,26718,26445,26154,25919,25702,25523,25376,25273,25201,25122,25098,25052,24899,24604,24204,23779,23281,22866,22580,22351,22092,21767,21450,21068,20662,20343,20125,19967,19849,19767,19684,19533,19288,18898,18385,17853,17329,16929,16618,16473,16410,16448,16478,16460,16429,16364,16229,16042,15806,15543,15164,14734,14256,13770,13274,12742,12224,11668,11064,10458,9836,9240,8679,8162,7676,7215,6733,6251,5787,5319,4867,4426,4028,3653,3309,2987,2679,2415,2148,1932,1720,1513,1344,1182,1034,908,774,666,570,477,360,308,273,217,276,524,742504,691657,1434161
2,5,Antioquia,2018,Total,45886,45988,46080,46199,46338,46490,46705,46960,47265,47635,48088,48633,49251,49970,50740,51615,52544,53499,54557,55615,56404,56984,57267,57261,56970,56568,56039,55250,54112,52777,51491,50302,49267,48512,47885,47231,46423,45270,43645,41698,39706,37760,36245,35335,34971,34801,34834,35056,35470,35948,36359,36678,36667,36215,35441,34467,33367,32123,30898,29614,28258,26890,25510,24146,22799,21494,20211,18943,17772,16648,15531,14437,13375,12298,11256,10267,9306,8423,7594,6853,6138,5490,4900,4366,3872,3426,3018,2650,2311,2011,1754,1496,1287,1088,909,722,581,532,495,540,1193,43949,44022,44121,44201,44355,44476,44694,44913,45221,45598,46045,46577,47212,47928,48741,49653,50644,51731,52971,54226,55273,56116,56665,56907,56827,56619,56256,55642,54705,53592,52532,51553,50804,50353,50114,49822,49399,48612,47325,45682,43997,42358,41134,40501,40376,40470,40767,41257,41902,42635,43271,43756,43884,43484,42709,41725,40512,39188,37825,36406,34888,33314,31742,30156,28601,27048,25523,24062,22651,21270,19946,18614,17309,15975,14692,13409,12196,11065,10010,9035,8150,7309,6555,5845,5222,4644,4104,3623,3202,2810,2455,2119,1835,1568,1334,1094,895,816,720,839,2065,89835,90010,90201,90400,90693,90966,91399,91873,92486,93233,94133,95210,96463,97898,99481,101268,103188,105230,107528,109841,111677,113100,113932,114168,113797,113187,112295,110892,108817,106369,104023,101855,100071,98865,97999,97053,95822,93882,90970,87380,83703,80118,77379,75836,75347,75271,75601,76313,77372,78583,79630,80434,80551,79699,78150,76192,73879,71311,68723,66020,63146,60204,57252,54302,51400,48542,45734,43005,40423,37918,35477,33051,30684,28273,25948,23676,21502,19488,17604,15888,14288,12799,11455,10211,9094,8070,7122,6273,5513,4821,4209,3615,3122,2656,2243,1816,1476,1348,1215,1379,3258,3094159,3312943,6407102
99,8,Atlántico,2018,Cabecera Municipal,20413,20427,20443,20463,20488,20520,20555,20597,20646,20711,20788,20874,20973,21072,21180,21272,21353,21388,21345,21245,21099,20885,20681,20547,20433,20263,20042,19747,19337,18868,18450,18080,17767,17557,17387,17200,16968,16619,16138,15558,14952,14365,13860,13475,13202,13016,12904,12842,12822,12807,12779,12700,12572,12375,12106,11785,11421,10998,10522,10015,9499,8968,8461,7979,7527,7076,6650,6219,5795,5383,4976,4581,4216,3872,3555,3244,2951,2674,2417,2188,1964,1764,1582,1411,1253,1119,985,873,765,670,584,504,434,372,311,255,203,184,173,189,474,19456,19499,19547,19595,19657,19711,19784,19853,19945,20040,20147,20276,20407,20556,20704,20863,21010,21102,21129,21081,21013,20867,20752,20697,20669,20569,20412,20173,19843,19450,19105,18802,18574,18452,18386,18305,18166,17911,17504,16980,16423,15894,15434,15108,14886,14765,14707,14695,14736,14779,14791,14757,14652,14459,14187,13848,13450,12995,12480,11933,11365,10788,10223,9694,9202,8711,8240,7765,7273,6778,6304,5840,5407,5002,4622,4246,3883,3545,3226,2936,2664,2411,2176,1967,1767,1589,1420,1269,1132,1002,889,780,682,595,509,430,354,330,307,336,1004,39869,39926,39990,40058,40145,40231,40339,40450,40591,40751,40935,41150,41380,41628,41884,42135,42363,42490,42474,42326,42112,41752,41433,41244,41102,40832,40454,39920,39180,38318,37555,36882,36341,36009,35773,35505,35134,34530,33642,32538,31375,30259,29294,28583,28088,27781,27611,27537,27558,27586,27570,27457,27224,26834,26293,25633,24871,23993,23002,21948,20864,19756,18684,17673,16729,15787,14890,13984,13068,12161,11280,10421,9623,8874,8177,7490,6834,6219,5643,5124,4628,4175,3758,3378,3020,2708,2405,2142,1897,1672,1473,1284,1116,967,820,685,557,514,480,525,1478,1166197,1238634,2404831
100,8,Atlántico,2018,Centros Poblados y Rural Disperso,1300,1288,1272,1262,1246,1232,1227,1208,1205,1198,1186,1186,1174,1174,1171,1172,1168,1158,1157,1151,1132,1127,1111,1109,1103,1100,1094,1084,1055,1022,1000,975,959,943,929,918,902,888,872,862,848,833,830,821,824,823,831,833,822,812,793,769,752,738,730,713,696,668,640,605,571,531,500,478,466,441,428,416,397,364,352,329,309,291,265,246,226,204,194,173,158,142,129,119,105,98,87,75,68,64,54,48,38,34,34,21,17,14,16,25,19,1240,1224,1211,1196,1186,1169,1161,1144,1139,1127,1120,1113,1112,1104,1100,1103,1100,1092,1092,1080,1072,1062,1051,1050,1047,1039,1042,1019,998,961,938,912,890,878,870,860,852,837,824,802,779,761,744,734,731,728,733,733,719,705,687,665,648,635,619,605,590,569,538,509,475,446,419,399,381,365,353,339,318,302,285,265,252,234,221,205,186,178,161,150,135,126,114,104,95,85,83,71,65,56,50,46,36,40,28,23,15,17,14,25,28,2540,2512,2483,2458,2432,2401,2388,2352,2344,2325,2306,2299,2286,2278,2271,2275,2268,2250,2249,2231,2204,2189,2162,2159,2150,2139,2136,2103,2053,1983,1938,1887,1849,1821,1799,1778,1754,1725,1696,1664,1627,1594,1574,1555,1555,1551,1564,1566,1541,1517,1480,1434,1400,1373,1349,1318,1286,1237,1178,1114,1046,977,919,877,847,806,781,755,715,666,637,594,561,525,486,451,412,382,355,323,293,268,243,223,200,183,170,146,133,120,104,94,74,74,62,44,32,31,30,50,47,68247,62439,130686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3070,97,Vaupés,2018,Centros Poblados y Rural Disperso,544,539,533,531,525,522,517,510,507,502,495,484,478,465,453,440,418,391,360,319,276,241,208,192,181,172,167,158,149,144,137,131,131,126,123,123,121,119,117,117,111,112,109,108,104,106,101,99,95,89,86,76,74,71,71,74,73,72,68,62,58,52,48,49,47,45,46,46,42,36,34,28,24,22,21,14,17,16,12,10,10,6,7,7,5,5,4,5,2,2,1,3,2,4,0,0,1,0,0,2,1,509,508,512,511,511,513,511,506,504,496,487,476,458,440,414,385,352,315,282,249,214,181,157,143,133,133,129,121,120,111,104,107,103,98,99,98,98,93,93,88,87,82,81,78,75,75,74,72,68,65,60,57,54,54,57,58,59,59,54,53,45,44,41,38,39,36,34,33,33,27,28,25,19,21,22,22,22,24,23,21,21,21,22,21,17,21,18,16,15,13,14,11,11,8,9,5,5,3,1,7,6,1053,1047,1045,1042,1036,1035,1028,1016,1011,998,982,960,936,905,867,825,770,706,642,568,490,422,365,335,314,305,296,279,269,255,241,238,234,224,222,221,219,212,210,205,198,194,190,186,179,181,175,171,163,154,146,133,128,125,128,132,132,131,122,115,103,96,89,87,86,81,80,79,75,63,62,53,43,43,43,36,39,40,35,31,31,27,29,28,22,26,22,21,17,15,15,14,13,12,9,5,6,3,1,9,7,15161,13546,28707
3071,97,Vaupés,2018,Total,631,638,638,648,651,655,659,660,663,665,664,657,659,649,641,630,612,579,542,485,432,378,331,306,288,271,256,239,230,223,219,215,214,206,198,192,186,178,176,175,170,169,165,163,157,157,153,151,143,138,135,124,118,118,116,119,118,114,111,103,96,89,83,81,75,72,71,66,62,52,45,38,32,28,28,22,23,23,19,17,15,12,12,11,10,8,9,8,5,5,2,7,3,5,1,3,1,1,0,3,1,592,604,618,631,644,655,661,666,669,669,663,655,637,618,589,553,514,466,422,379,331,287,253,233,223,219,211,203,200,191,184,187,185,174,170,161,158,148,146,141,140,135,131,128,124,126,124,121,119,114,111,105,104,102,102,101,101,99,92,89,78,75,69,63,64,57,55,54,49,43,41,35,30,30,30,30,27,29,28,24,24,24,24,22,19,21,19,16,15,13,14,11,11,8,10,5,5,3,4,8,7,1223,1242,1256,1279,1295,1310,1320,1326,1332,1334,1327,1312,1296,1267,1230,1183,1126,1045,964,864,763,665,584,539,511,490,467,442,430,414,403,402,399,380,368,353,344,326,322,316,310,304,296,291,281,283,277,272,262,252,246,229,222,220,218,220,219,213,203,192,174,164,152,144,139,129,126,120,111,95,86,73,62,58,58,52,50,52,47,41,39,36,36,33,29,29,28,24,20,18,16,18,14,13,11,8,6,4,4,11,8,21425,19372,40797
3168,99,Vichada,2018,Cabecera Municipal,259,261,257,257,256,256,255,256,256,259,260,265,270,275,280,286,290,294,296,296,294,286,281,273,263,250,237,224,221,215,213,210,207,206,204,199,199,195,190,187,183,180,174,163,154,144,135,129,124,125,123,123,120,116,108,106,96,90,85,81,78,71,68,64,56,55,51,46,44,40,38,36,32,29,27,23,20,18,16,13,11,10,7,7,5,4,3,2,3,1,1,0,1,0,3,0,0,0,1,2,4,240,243,244,245,246,246,249,251,247,251,250,250,250,247,247,246,245,242,240,235,233,227,223,225,222,219,223,221,217,214,212,212,210,208,204,201,196,193,188,185,181,177,170,161,146,138,127,122,117,120,119,119,119,113,106,101,94,88,83,80,75,72,67,65,57,54,51,47,40,36,32,25,19,20,15,16,14,13,11,11,8,10,7,7,7,6,4,4,4,3,3,2,2,4,1,2,1,0,1,2,0,499,504,501,502,502,502,504,507,503,510,510,515,520,522,527,532,535,536,536,531,527,513,504,498,485,469,460,445,438,429,425,422,417,414,408,400,395,388,378,372,364,357,344,324,300,282,262,251,241,245,242,242,239,229,214,207,190,178,168,161,153,143,135,129,113,109,102,93,84,76,70,61,51,49,42,39,34,31,27,24,19,20,14,14,12,10,7,6,7,4,4,2,3,4,4,2,1,0,2,4,4,13387,12446,25833
3169,99,Vichada,2018,Centros Poblados y Rural Disperso,1160,1168,1174,1185,1192,1197,1204,1204,1203,1199,1190,1176,1162,1139,1113,1087,1055,1018,979,936,892,843,799,759,720,684,647,615,588,568,552,539,529,511,497,482,465,453,445,438,427,421,413,399,386,374,366,359,351,340,330,321,313,302,297,285,275,263,245,228,210,190,176,165,151,144,134,128,116,103,94,83,74,68,62,57,51,47,42,37,34,29,27,23,21,19,15,15,12,9,9,8,5,6,5,3,4,1,0,6,10,1111,1119,1124,1129,1133,1138,1135,1135,1128,1118,1102,1085,1061,1033,1002,965,933,889,850,804,760,718,678,645,617,592,570,549,526,508,487,475,457,444,427,410,396,382,371,364,353,345,336,321,310,296,286,277,266,254,241,229,219,212,204,196,190,179,170,157,148,133,123,115,109,107,99,93,86,76,69,59,52,47,43,41,34,32,29,25,23,21,19,16,14,12,12,9,8,7,6,5,4,4,1,5,1,2,1,2,17,2271,2287,2298,2314,2325,2335,2339,2339,2331,2317,2292,2261,2223,2172,2115,2052,1988,1907,1829,1740,1652,1561,1477,1404,1337,1276,1217,1164,1114,1076,1039,1014,986,955,924,892,861,835,816,802,780,766,749,720,696,670,652,636,617,594,571,550,532,514,501,481,465,442,415,385,358,323,299,280,260,251,233,221,202,179,163,142,126,115,105,98,85,79,71,62,57,50,46,39,35,31,27,24,20,16,15,13,9,10,6,8,5,3,1,8,27,43855,38120,81975
3170,99,Vichada,2018,Total,1419,1429,1431,1442,1448,1453,1459,1460,1459,1458,1450,1441,1432,1414,1393,1373,1345,1312,1275,1232,1186,1129,1080,1032,983,934,884,839,809,783,765,749,736,717,701,681,664,648,635,625,610,601,587,562,540,518,501,488,475,465,453,444,433,418,405,391,371,353,330,309,288,261,244,229,207,199,185,174,160,143,132,119,106,97,89,80,71,65,58,50,45,39,34,30,26,23,18,17,15,10,10,8,6,6,8,3,4,1,1,8,14,1351,1362,1368,1374,1379,1384,1384,1386,1375,1369,1352,1335,1311,1280,1249,1211,1178,1131,1090,1039,993,945,901,870,839,811,793,770,743,722,699,687,667,652,631,611,592,575,559,549,534,522,506,482,456,434,413,399,383,374,360,348,338,325,310,297,284,267,253,237,223,205,190,180,166,161,150,140,126,112,101,84,71,67,58,57,48,45,40,36,31,31,26,23,21,18,16,13,12,10,9,7,6,8,2,7,2,2,2,4,17,2770,2791,2799,2816,2827,2837,2843,2846,2834,2827,2802,2776,2743,2694,2642,2584,2523,2443,2365,2271,2179,2074,1981,1902,1822,1745,1677,1609,1552,1505,1464,1436,1403,1369,1332,1292,1256,1223,1194,1174,1144,1123,1093,1044,996,952,914,887,858,839,813,792,771,743,715,688,655,620,583,546,511,466,434,409,373,360,335,314,286,255,233,203,177,164,147,137,119,110,98,86,76,70,60,53,47,41,34,30,27,20,19,15,12,14,10,10,6,3,3,12,31,57242,50566,107808

In [4]:
df18.groupby(['DP','DPNOM']).agg({'Total':'sum','Total Hombres':'sum','Total Mujeres':'sum'}).reset_index()

    DP                       DPNOM     Total  Total Hombres  Total Mujeres
0    5                   Antioquia  12814204        6188318        6625886
1    8                   Atlántico   5071034        2468888        2602146
2   11                Bogotá, D.C.  14825132        7088156        7736976
3   13                     Bolívar   4140220        2054646        2085574
4   15                      Boyacá   2434752        1198586        1236166
5   17                      Caldas   1996510         967476        1029034
6   18                     Caquetá    803698         407608         396090
7   19                       Cauca   2928976        1450548        1478428
8   20                       Cesar   2401148        1188660        1212488
9   23                     Córdoba   3569566        1777096        1792470
10  25                Cundinamarca   5838120        2884400        2953720
11  27                       Chocó   1069652         528456         541196
12  41                       Huila   2200772        1098188        1102584
13  44                  La Guajira   1761120         862494         898626
14  47                   Magdalena   2683492        1343038        1340454
15  50                        Meta   2079444        1051806        1027638
16  52                      Nariño   3261184        1596390        1664794
17  54          Norte de Santander   2983378        1470986        1512392
18  63                     Quindio   1079808         520502         559306
19  66                   Risaralda   1886802         902836         983966
20  68                   Santander   4369674        2139198        2230476
21  70                       Sucre   1809726         909976         899750
22  73                      Tolima   2660374        1318572        1341802
23  76             Valle del Cauca   8951772        4253092        4698680
24  81                      Arauca    524348         265038         259310
25  85                    Casanare    841008         425096         415912
26  86                    Putumayo    696364         351382         344982
27  88  Archipiélago de San Andrés    122560          59190          63370
28  91                    Amazonas    153178          79822          73356
29  94                     Guainía     96228          50276          45952
30  95                    Guaviare    165534          88520          77014
31  97                      Vaupés     81594          42850          38744
32  99                     Vichada    215616         114484         101132

In [5]:
n18=pd.read_parquet("../parquet_datasets/nac2018.parquet")
n18

,COD_DPTO,COD_MUNIC,AREANAC,SIT_PARTO,OTRO_SIT,SEXO,PESO_NAC,TALLA_NAC,ANO,MES,ATEN_PAR,T_GES,NUMCONSUL,TIPO_PARTO,MUL_PARTO,APGAR1,APGAR2,IDHEMOCLAS,IDFACTORRH,IDPERTET,EDAD_MADRE,EST_CIVM,NIV_EDUM,ULTCURMAD,CODPRES,CODPTORE,CODMUNRE,AREA_RES,N_HIJOSV,FECHA_NACM,N_EMB,SEG_SOCIAL,IDCLASADMI,EDAD_PADRE,NIV_EDUP,ULTCURPAD,PROFESION
0,5,1,1,1,,1,7,5,2018,1,1,4,8,1,1,8,10,1,1,6,4,1,4,11,170,27,1,1,2,13/08/2014,2,1,1,30,4,11,1
1,11,1,1,1,,1,6,5,2018,1,1,4,9,1,1,9,10,1,1,6,5,6,9,5,170,11,1,1,1,,1,1,1,36,9,5,1
2,52,1,1,1,,1,6,5,2018,1,1,3,11,2,1,7,10,4,1,6,4,1,5,11,170,52,885,1,2,15/02/2011,3,2,2,27,4,11,1
3,11,1,1,1,,1,6,5,2018,1,1,4,8,2,1,8,9,3,1,6,5,1,9,5,170,11,1,1,1,,2,1,1,32,9,5,1
4,50,1,1,1,,1,5,4,2018,1,1,4,8,2,1,8,9,3,1,6,3,2,9,4,170,50,6,3,1,,1,2,2,21,4,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649110,54,1,1,1,,2,6,4,2018,10,1,4,1,2,1,8,10,3,1,6,3,1,3,7,170,54,1,1,2,11/01/2011,2,2,2,29,99,99,1
649111,27,1,1,1,,1,6,5,2018,9,1,3,5,1,1,7,10,3,1,5,4,9,99,99,170,27,1,1,1,,1,2,2,35,99,99,1
649112,70,1,1,1,,1,6,4,2018,10,1,4,6,2,1,8,9,3,1,6,5,1,9,5,170,70,742,1,1,,3,1,1,57,9,5,1
649113,11,1,1,1,,2,5,5,2018,10,1,4,5,1,1,8,9,3,1,6,2,2,2,5,170,11,1,1,1,,1,2,2,18,99,99,1
649114,11,1,1,1,,2,6,5,2018,10,1,4,9,1,1,9,10,2,1,6,4,6,9,5,170,11,1,1,2,31/07/2012,2,1,1,42,7,2,1

In [6]:
d18 = pd.read_parquet("../parquet_datasets/nofetal2018_new.parquet")
d18

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,ULTCURFAL,MUERTEPORO,SIMUERTEPO,OCUPACION,IDPERTET,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,IDADMISALUD,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,ULTCURMAD,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,C_MUERTEB,C_MUERTEC,C_MUERTED,C_MUERTEE,ASIS_MED,C_DIR1,C_DIR12,C_ANT1,C_ANT12,C_ANT2,C_ANT22,C_ANT3,C_ANT32,C_PAT1,C_PAT2,C_BAS1,C_MCM1,CAUSA_667,IDPROFCER,CAU_HOMOL
0,Caldas,50,Cabecera municipal,Vía pública,,Defunción no fetal,2018,Enero,15,5,Masculino,Estaba casado(a),De 50 a 54 años,De 45 a 64 años,Profesional,5,2,,CONTADORES,Ninguno de las anteriores,Colombia,Caldas,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R570,,I219,,,,,,,,I219,,303,1,51
1,Caqueta,592,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,8,15,Masculino,Estaba viudo(a),De 85 a 89 años,De 65 y mas años,Básica primaria,5,2,,AGRICULTORES DE CULTIVOS TRANSITORIOS,Ninguno de las anteriores,Colombia,Caqueta,592,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,R570,,R688,,E43,,,,R011,,E43,,602,1,42
2,Caldas,13,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,10,0,Femenino,Estaba viudo(a),De 95 a 99 años,De 65 y mas años,Ninguno,0,2,,COCINEROS Y AFINES,Ninguno de las anteriores,Colombia,Caldas,13,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,I219,,,,,,,,I10,E785,I219,,303,1,51
3,Antioquia,1,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,12,15,Masculino,Estaba casado(a),De 80 a 84 años,De 65 y mas años,Básica primaria,5,2,,PENSIONADO,Ninguno de las anteriores,Colombia,Antioquia,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R090,,C20,,,,,,,,C20,,203,1,14
4,Meta,1,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,11,0,Femenino,No estaba casado(a) y llevaba dos o más años v...,De 85 a 89 años,De 65 y mas años,Básica primaria,3,2,,HOGAR,Ninguno de las anteriores,Colombia,Meta,226,Cabecera municipal,Subsidiado,2,Natural,Médico tratante,,,,,,,,,,,0,,,,,,,,1,1,,,Sí,K650,,K658,,K358,K388,,,I119,,K352,,607,1,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236927,Sucre,265,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Abril,22,44,Masculino,Sin información,De 50 a 54 años,De 45 a 64 años,Sin información,99,2,,OTROS TRABAJADORES DE SERVICIOS PERSONALES A P...,Ninguno de las anteriores,Colombia,Sucre,265,1,Subsidiado,2,Natural,Médico tratante,,,,,,,,,,,0,,,,,,,,1,,,,Sí,R578,,A419,,K922,,,,,,A419,,106,1,"Septicemia, excepto neonatal"
236928,Risaralda,1,"Centro poblado (Inspección, corregimiento o ca...",Casa /domicilio,,Defunción no fetal,2018,Diciembre,17,45,Masculino,Estaba viudo(a),De 70 a 74 años,De 65 y mas años,Media académica o clásica,11,2,,ELECTRICISTAS DE OBRAS Y AFINES,Ninguno de las anteriores,Colombia,Risaralda,1,2,Excepción,5,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,R571,,K922,,D375,,,,,,D375,,215,1,37
236929,Risaralda,1,Rural disperso,Otro,HOGAR DE ANCIANOS,Defunción no fetal,2018,Diciembre,9,10,Masculino,Estaba soltero(a),De 90 a 94 años,De 65 y mas años,Profesional,5,2,,SIN INFORMACION,Ninguno de las anteriores,Colombia,Risaralda,1,3,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,I469,,C07,,E43,,,,,,C07,,214,1,11
236930,Santander,207,Rural disperso,Casa /domicilio,,Defunción no fetal,2018,Julio,1,0,Femenino,Estaba soltero(a),De 80 a 84 años,De 65 y mas años,Sin información,99,2,,AGRICULTORES DE CULTIVOS PERMANENTES (PLANTACI...,Ninguno de las anteriores,Colombia,Santander,207,3,Subsidiado,2,Natural,Médico tratante,,,,,,,,,,,0,,,,,,,,1,,,,Sí,A419,,B879,,C760,,,,,,C760,,214,1,33
236931,Valle del Cauca,109,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Agosto,18,30,Masculino,Sin información,De 65 a 69 años,De 65 y mas años,Básica primaria,5,2,,HOGAR,Ninguno de las anteriores,Colombia,Valle del Cauca,109,1,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,,,Sí,R570,,I219,,I10,,,,N185,,I219,,303,1,51

## Create adjusted Demographics 2018

In [7]:
df18.columns

Index(['DP', 'DPNOM', 'AÑO', 'ÁREA GEOGRÁFICA', 'Hombres_0', 'Hombres_1',
       'Hombres_2', 'Hombres_3', 'Hombres_4', 'Hombres_5',
       ...
       'Total_94', 'Total_95', 'Total_96', 'Total_97', 'Total_98', 'Total_99',
       'Total_100 y más', 'Total Hombres', 'Total Mujeres', 'Total'],
      dtype='object', length=310)

In [8]:
df18_2=df18.melt(id_vars=df18.columns[0:4],var_name='Dato',value_name='Número')
df18_2

,DP,DPNOM,AÑO,ÁREA GEOGRÁFICA,Dato,Número
0,5,Antioquia,2018,Cabecera Municipal,Hombres_0,31398
1,5,Antioquia,2018,Centros Poblados y Rural Disperso,Hombres_0,14488
2,5,Antioquia,2018,Total,Hombres_0,45886
3,8,Atlántico,2018,Cabecera Municipal,Hombres_0,20413
4,8,Atlántico,2018,Centros Poblados y Rural Disperso,Hombres_0,1300
...,...,...,...,...,...,...
30289,97,Vaupés,2018,Centros Poblados y Rural Disperso,Total,28707
30290,97,Vaupés,2018,Total,Total,40797
30291,99,Vichada,2018,Cabecera Municipal,Total,25833
30292,99,Vichada,2018,Centros Poblados y Rural Disperso,Total,81975
30293,99,Vichada,2018,Total,Total,107808

In [9]:
df18_2.groupby(['DP','DPNOM']).sum().reset_index()

    DP                       DPNOM      AÑO    Número
0    5                   Antioquia  1852524  51256816
1    8                   Atlántico  1852524  20284136
2   11                Bogotá, D.C.  1852524  59300528
3   13                     Bolívar  1852524  16560880
4   15                      Boyacá  1852524   9739008
5   17                      Caldas  1852524   7986040
6   18                     Caquetá  1852524   3214792
7   19                       Cauca  1852524  11715904
8   20                       Cesar  1852524   9604592
9   23                     Córdoba  1852524  14278264
10  25                Cundinamarca  1852524  23352480
11  27                       Chocó  1852524   4278608
12  41                       Huila  1852524   8803088
13  44                  La Guajira  1852524   7044480
14  47                   Magdalena  1852524  10733968
15  50                        Meta  1852524   8317776
16  52                      Nariño  1852524  13044736
17  54          Norte de Santander  1852524  11933512
18  63                     Quindio  1852524   4319232
19  66                   Risaralda  1852524   7547208
20  68                   Santander  1852524  17478696
21  70                       Sucre  1852524   7238904
22  73                      Tolima  1852524  10641496
23  76             Valle del Cauca  1852524  35807088
24  81                      Arauca  1852524   2097392
25  85                    Casanare  1852524   3364032
26  86                    Putumayo  1852524   2785456
27  88  Archipiélago de San Andrés  1852524    490240
28  91                    Amazonas  1852524    612712
29  94                     Guainía  1852524    384912
30  95                    Guaviare  1852524    662136
31  97                      Vaupés  1852524    326376
32  99                     Vichada  1852524    862464

In [10]:
df18_2[['Sexo','Edad']] = df18_2.Dato.str.split("_",expand=True)
df18_2[['Sexo','Edad']]

          Sexo  Edad
0      Hombres     0
1      Hombres     0
2      Hombres     0
3      Hombres     0
4      Hombres     0
...        ...   ...
30289    Total  None
30290    Total  None
30291    Total  None
30292    Total  None
30293    Total  None

[30294 rows x 2 columns]

In [11]:
df18_2[df18_2.Edad.isna()].Sexo.unique()

array(['Total Hombres', 'Total Mujeres', 'Total'], dtype=object)

In [12]:
df18_2.Edad.fillna('999',inplace=True)
df18_2.Edad.replace({'100 y más':'100'},inplace=True)
df18_2.Edad.unique()

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
       '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
       '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
       '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67',
       '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
       '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100',
       '999'], dtype=object)

In [13]:
df18_2['Edad']=df18_2.Edad.astype('int')
#df['new column name'] = df['column name'].apply(lambda x: 'value if condition is met' if x condition else 'value if condition is not met')
df18_2.Edad.value_counts()

95    297
37    297
99    297
4     297
20    297
     ...
74    297
90    297
11    297
27    297
0     297
Name: Edad, Length: 102, dtype: int64

In [14]:
seg=list(range(0, 109, 5))
df18_2['RangoEdad']= pd.cut(df18_2.Edad,seg,right=False).astype('str').replace('nan',np.NaN)
df18_2.RangoEdad.value_counts()

[25.0, 30.0)      1485
[45.0, 50.0)      1485
[50.0, 55.0)      1485
[10.0, 15.0)      1485
[30.0, 35.0)      1485
[20.0, 25.0)      1485
[80.0, 85.0)      1485
[0.0, 5.0)        1485
[95.0, 100.0)     1485
[85.0, 90.0)      1485
[5.0, 10.0)       1485
[70.0, 75.0)      1485
[40.0, 45.0)      1485
[65.0, 70.0)      1485
[60.0, 65.0)      1485
[75.0, 80.0)      1485
[15.0, 20.0)      1485
[90.0, 95.0)      1485
[55.0, 60.0)      1485
[35.0, 40.0)      1485
[100.0, 105.0)     297
Name: RangoEdad, dtype: int64

In [15]:
df18_2.RangoEdad.isna().sum()

297

In [16]:
df18_2[df18_2.RangoEdad.isna()].Edad.unique()

array([999])

In [17]:
df18_3=df18_2[df18_2.Sexo!='Total'].groupby(['DP','DPNOM','Sexo','RangoEdad']).sum()['Número'].reset_index()
df18_3

      DP      DPNOM     Sexo       RangoEdad  Número
0      5  Antioquia  Hombres      [0.0, 5.0)  460982
1      5  Antioquia  Hombres    [10.0, 15.0)  493364
2      5  Antioquia  Hombres  [100.0, 105.0)    2386
3      5  Antioquia  Hombres    [15.0, 20.0)  535660
4      5  Antioquia  Hombres    [20.0, 25.0)  569772
...   ..        ...      ...             ...     ...
1381  99    Vichada  Mujeres    [75.0, 80.0)     452
1382  99    Vichada  Mujeres    [80.0, 85.0)     264
1383  99    Vichada  Mujeres    [85.0, 90.0)     138
1384  99    Vichada  Mujeres    [90.0, 95.0)      64
1385  99    Vichada  Mujeres   [95.0, 100.0)      34

[1386 rows x 5 columns]

In [18]:
df18_3.RangoEdad.isna().sum()

0

In [19]:
df18_3.Sexo.unique()

array(['Hombres', 'Mujeres'], dtype=object)

## Mortality 2018 adjustments

In [20]:
d18.head()

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,ULTCURFAL,MUERTEPORO,SIMUERTEPO,OCUPACION,IDPERTET,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,IDADMISALUD,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,ULTCURMAD,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,C_MUERTEB,C_MUERTEC,C_MUERTED,C_MUERTEE,ASIS_MED,C_DIR1,C_DIR12,C_ANT1,C_ANT12,C_ANT2,C_ANT22,C_ANT3,C_ANT32,C_PAT1,C_PAT2,C_BAS1,C_MCM1,CAUSA_667,IDPROFCER,CAU_HOMOL
0,Caldas,50,Cabecera municipal,Vía pública,,Defunción no fetal,2018,Enero,15,5,Masculino,Estaba casado(a),De 50 a 54 años,De 45 a 64 años,Profesional,5,2,,CONTADORES,Ninguno de las anteriores,Colombia,Caldas,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R570,,I219,,,,,,,,I219,,303,1,51
1,Caqueta,592,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,8,15,Masculino,Estaba viudo(a),De 85 a 89 años,De 65 y mas años,Básica primaria,5,2,,AGRICULTORES DE CULTIVOS TRANSITORIOS,Ninguno de las anteriores,Colombia,Caqueta,592,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,R570,,R688,,E43,,,,R011,,E43,,602,1,42
2,Caldas,13,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,10,0,Femenino,Estaba viudo(a),De 95 a 99 años,De 65 y mas años,Ninguno,0,2,,COCINEROS Y AFINES,Ninguno de las anteriores,Colombia,Caldas,13,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,I219,,,,,,,,I10,E785,I219,,303,1,51
3,Antioquia,1,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,12,15,Masculino,Estaba casado(a),De 80 a 84 años,De 65 y mas años,Básica primaria,5,2,,PENSIONADO,Ninguno de las anteriores,Colombia,Antioquia,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R090,,C20,,,,,,,,C20,,203,1,14
4,Meta,1,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,11,0,Femenino,No estaba casado(a) y llevaba dos o más años v...,De 85 a 89 años,De 65 y mas años,Básica primaria,3,2,,HOGAR,Ninguno de las anteriores,Colombia,Meta,226,Cabecera municipal,Subsidiado,2,Natural,Médico tratante,,,,,,,,,,,0,,,,,,,,1,1,,,Sí,K650,,K658,,K358,K388,,,I119,,K352,,607,1,65

In [21]:
d18.COD_DPTO.unique()

array(['Caldas', 'Caqueta', 'Antioquia', 'Meta', 'Bogotá', 'Santander',
       'Nariño', 'La guajira', 'Atlántico', 'Risaralda',
       'Valle del Cauca', 'Boyaca', 'Quindio', 'Magdalena',
       'Cundinamarca', 'Tolima', 'Cordoba', 'Putumayo', 'Bolivar',
       'Vichada', 'Cesar', 'Cauca', 'Norte de Santander', 'Huila',
       'Casanare', 'Sucre', 'Arauca', 'Guaviare', 'Choco',
       'Archipiélago de San Andrés, Providencia y Santa Catalina',
       'Amazonas', 'Guainía', 'Vaupés'], dtype=object)

In [22]:
Deptos={ 5: 'Antioquia', 8: 'Atlántico', 11: 'Bogotá', 13: 'Bolivar', 15: 'Boyaca', 17: 'Caldas', 18: 'Caqueta', 19: 'Cauca', 20: 'Cesar', 23: 'Cordoba', 25: 'Cundinamarca', 27: 'Choco', 41: 'Huila', 44: 'La guajira', 47: 'Magdalena', 50: 'Meta', 52: 'Nariño', 54: 'Norte de Santander', 63: 'Quindio', 66: 'Risaralda', 68: 'Santander', 70: 'Sucre', 73: 'Tolima', 76: 'Valle del Cauca', 81: 'Arauca', 85: 'Casanare', 86: 'Putumayo', 88: 'Archipiélago de San Andrés, Providencia y Santa Catalina', 91: 'Amazonas', 94: 'Guainía', 95: 'Guaviare', 97: 'Vaupés', 99: 'Vichada'}
DeptosInv={'Antioquia': 5, 'Atlántico': 8, 'Bogotá': 11, 'Bolivar': 13, 'Boyaca': 15, 'Caldas': 17, 'Caqueta': 18, 'Cauca': 19, 'Cesar': 20, 'Cordoba': 23, 'Cundinamarca': 25, 'Choco': 27, 'Huila': 41, 'La guajira': 44, 'Magdalena': 47, 'Meta': 50, 'Nariño': 52, 'Norte de Santander': 54, 'Quindio': 63, 'Risaralda': 66, 'Santander': 68, 'Sucre': 70, 'Tolima': 73, 'Valle del Cauca': 76, 'Arauca': 81, 'Casanare': 85, 'Putumayo': 86, 'Archipiélago de San Andrés, Providencia y Santa Catalina': 88, 'Amazonas': 91, 'Guainía': 94, 'Guaviare': 95, 'Vaupés': 97, 'Vichada': 99}

d18['COD_DPTO2']=d18.COD_DPTO.map(DeptosInv)

In [23]:
d18.COD_DPTO2.unique()

array([17, 18,  5, 50, 11, 68, 52, 44,  8, 66, 76, 15, 63, 47, 25, 73, 23,
       86, 13, 99, 20, 19, 54, 41, 85, 70, 81, 95, 27, 88, 91, 94, 97])

In [24]:
d18.GRU_ED1.unique()

array(['De 50 a 54 años', 'De 85 a 89 años', 'De 95 a 99 años',
       'De 80 a 84 años', 'De 75 a 79 años', 'De 90 a 94 años',
       'De 1 a 5 meses', 'De 65 a 69 años', 'De 45 a 49 años',
       'De 60 a 64 años', 'De 15 a 19 años', 'De 70 a 74 años',
       'De 30 a 34 años', 'De 55 a 59 años', 'De 20 a 24 años',
       'De 25 a 29 años', 'De 40 a 44 años', 'De 10 a 14 años',
       'De 35 a 39 años', 'De 6 a 11 meses', 'De 5 a 9 años',
       'De 100 años y más', 'De 1 año', 'De 2 a 4 años', 'De 7 a 27 días',
       'Menor de un día', 'De 1 a 6 días', 'Menor de una hora',
       'De 28 a 29 días', 'Edad desconocida'], dtype=object)

In [25]:
#Replace all 0-4 years by the actual segment needed.
g04=['Menor de una hora','Menor de un día', 'De 1 a 6 días','De 7 a 27 días','De 28 a 29 días',
   'De 1 a 5 meses','De 6 a 11 meses','De 1 año', 'De 2 a 4 años']
d18.loc[ d18.GRU_ED1.isin(g04),'GRU_ED1']='De 0 a 4 años'
d18.GRU_ED1.unique()

array(['De 50 a 54 años', 'De 85 a 89 años', 'De 95 a 99 años',
       'De 80 a 84 años', 'De 75 a 79 años', 'De 90 a 94 años',
       'De 0 a 4 años', 'De 65 a 69 años', 'De 45 a 49 años',
       'De 60 a 64 años', 'De 15 a 19 años', 'De 70 a 74 años',
       'De 30 a 34 años', 'De 55 a 59 años', 'De 20 a 24 años',
       'De 25 a 29 años', 'De 40 a 44 años', 'De 10 a 14 años',
       'De 35 a 39 años', 'De 5 a 9 años', 'De 100 años y más',
       'Edad desconocida'], dtype=object)

In [26]:
d18[(d18.GRU_ED1=='Edad desconocida') | (d18.SEXO=='Indeterminado')].groupby(['SEXO','GRU_ED1','COD_DPTO']).count()

                                                    COD_MUNIC  A_DEFUN  \
SEXO          GRU_ED1           COD_DPTO
Femenino      Edad desconocida  Nariño                      1        1
Indeterminado De 0 a 4 años     Antioquia                   1        1
                                Atlántico                   1        1
                                Bogotá                      2        2
                                Santander                   1        1
                                Valle del Cauca             1        1
              De 100 años y más Bogotá                      1        1
                                Caqueta                     9        9
                                Huila                       3        3
                                Norte de Santander          1        1
                                Santander                   1        1
                                Valle del Cauca             1        1
              De 15 a 19 años   Bogotá                      4        4
                                Nariño                      1        1
                                Quindio                     1        1
              De 20 a 24 años   Huila                       1        1
                                Valle del Cauca             1        1
              De 25 a 29 años   Antioquia                   1        1
              De 30 a 34 años   Amazonas                    1        1
                                Arauca                      1        1
                                Nariño                      2        2
                                Valle del Cauca             1        1
              De 35 a 39 años   Nariño                      1        1
              De 40 a 44 años   Nariño                      2        2
                                Tolima                      1        1
              De 45 a 49 años   Bogotá                      1        1
                                Valle del Cauca             1        1
              De 5 a 9 años     Atlántico                   1        1
                                Bogotá                      1        1
              De 50 a 54 años   Atlántico                   1        1
                                Bogotá                      1        1
                                Cundinamarca                1        1
                                Putumayo                    1        1
                                Quindio                     1        1
                                Valle del Cauca             1        1
              De 55 a 59 años   Guaviare                    1        1
                                Tolima                      1        1
              De 60 a 64 años   Atlántico                   1        1
                                Bogotá                      1        1
                                Caldas                      1        1
              De 65 a 69 años   Antioquia                   1        1
              De 70 a 74 años   Bogotá                      3        3
                                Caldas                      1        1
              De 75 a 79 años   Bogotá                      1        1
                                Valle del Cauca             1        1
              De 80 a 84 años   Atlántico                   1        1
              De 90 a 94 años   Cauca                       1        1
                                Cundinamarca                1        1
              De 95 a 99 años   Antioquia                   2        2
                                Cauca                       1        1
                                Huila                       1        1
                                Norte de Santander          1        1
              Edad desconocida  Arauca                      1        1
                                Boyaca                      1        1
                                Choco                       1        1
                                Cundinamarca                3        3
                                Nariño                      3        3
                                Quindio                     2        2

                                                    SIT_DEFUN  OTRSITIODE  \
SEXO          GRU_ED1           COD_DPTO
Femenino      Edad desconocida  Nariño                      1           1
Indeterminado De 0 a 4 años     Antioquia                   1           1
                                Atlántico                   1           1
                                Bogotá                      2           2
                                Santander                   1           1
                                Valle del Cauca             1           1
              De 100 años y más Bogotá                      1           1
                                Caqueta                     9           9
                                Huila                       3           3
                                Norte de Santander          1           1
                                Santander                   1           1
                                Valle del Cauca             1           1
              De 15 a 19 años   Bogotá                      4           4
                                Nariño                      1           1
                                Quindio                     1           1
              De 20 a 24 años   Huila                       1           1
                                Valle del Cauca             1           1
              De 25 a 29 años   Antioquia                   1           1
              De 30 a 34 años   Amazonas                    1           1
                                Arauca                      1           1
                                Nariño                      2           2
                                Valle del Cauca             1           1
              De 35 a 39 años   Nariño                      1           1
              De 40 a 44 años   Nariño                      2           2
                                Tolima                      1           1
              De 45 a 49 años   Bogotá                      1           1
                                Valle del Cauca             1           1
              De 5 a 9 años     Atlántico                   1           1
                                Bogotá                      1           1
              De 50 a 54 años   Atlántico                   1           1
                                Bogotá                      1           1
                                Cundinamarca                1           1
                                Putumayo                    1           1
                                Quindio                     1           1
                                Valle del Cauca             1           1
              De 55 a 59 años   Guaviare                    1           1
                                Tolima                      1           1
              De 60 a 64 años   Atlántico                   1           1
                                Bogotá                      1           1
                                Caldas                      1           1
              De 65 a 69 años   Antioquia                   1           1
              De 70 a 74 años   Bogotá                      3           3
                                Caldas                      1           1
              De 75 a 79 años   Bogotá                      1           1
                                Valle del Cauca             1           1
              De 80 a 84 años   Atlántico                   1           1
              De 90 a 94 años   Cauca                       1           1
                                Cundinamarca                1           1
              De 95 a 99 años   Antioquia                   2           2
                                Cauca                       1           1
                                Huila                       1           1
                                Norte de Santander          1           1
              Edad desconocida  Arauca                      1           1
                                Boyaca                      1           1
                                Choco                       1           1
                                Cundinamarca                3           3
                                Nariño                      3           3
                                Quindio                     2           2

                                                    TIPO_DEFUN  ANO  MES  \
SEXO          GRU_ED1           COD_DPTO
Femenino      Edad desconocida  Nariño                       1    1    1
Indeterminado De 0 a 4 años     Antioquia                    1    1    1
                                Atlántico                    1    1    1
                                Bogotá                       2    2    2
                                Santander                    1    1    1
                                Valle del Cauca              1    1    1
              De 100 años y más Bogotá                       1    1    1
                                Caqueta                      9    9    9
                                Huila                        3    3    3
                                Norte de Santander           1    1    1
                                Santander                    1    1    1
                                Valle del Cauca              1    1    1
              De 15 a 19 años   Bogotá                       4    4    4
                                Nariño                       1    1    1
                                Quindio                      1    1    1
              De 20 a 24 años   Huila                        1    1    1
                                Valle del Cauca              1    1    1
              De 25 a 29 años   Antioquia                    1    1    1
              De 30 a 34 años   Amazonas                     1    1    1
                                Arauca                       1    1    1
                                Nariño                       2    2    2
                                Valle del Cauca              1    1    1
              De 35 a 39 años   Nariño                       1    1    1
              De 40 a 44 años   Nariño                       2    2    2
                                Tolima                       1    1    1
              De 45 a 49 años   Bogotá                       1    1    1
                                Valle del Cauca              1    1    1
              De 5 a 9 años     Atlántico                    1    1    1
                                Bogotá                       1    1    1
              De 50 a 54 años   Atlántico                    1    1    1
                                Bogotá                       1    1    1
                                Cundinamarca                 1    1    1
                                Putumayo                     1    1    1
                                Quindio                      1    1    1
                                Valle del Cauca              1    1    1
              De 55 a 59 años   Guaviare                     1    1    1
                                Tolima                       1    1    1
              De 60 a 64 años   Atlántico                    1    1    1
                                Bogotá                       1    1    1
                                Caldas                       1    1    1
              De 65 a 69 años   Antioquia                    1    1    1
              De 70 a 74 años   Bogotá                       3    3    3
                                Caldas                       1    1    1
              De 75 a 79 años   Bogotá                       1    1    1
                                Valle del Cauca              1    1    1
              De 80 a 84 años   Atlántico                    1    1    1
              De 90 a 94 años   Cauca                        1    1    1
                                Cundinamarca                 1    1    1
              De 95 a 99 años   Antioquia                    2    2    2
                                Cauca                        1    1    1
                                Huila                        1    1    1
                                Norte de Santander           1    1    1
              Edad desconocida  Arauca                       1    1    1
                                Boyaca                       1    1    1
                                Choco                        1    1    1
                                Cundinamarca                 3    3    3
                                Nariño                       3    3    3
                                Quindio                      2    2    2

                                                    HORA  MINUTOS  EST_CIVIL  \
SEXO          GRU_ED1           COD_DPTO
Femenino      Edad desconocida  Nariño                 1        1          1
Indeterminado De 0 a 4 años     Antioquia              1        1          1
                                Atlántico              1        1          1
                                Bogotá                 2        2          2
                                Santander              1        1          1
                                Valle del Cauca        1        1          1
              De 100 años y más Bogotá                 1        1          1
                                Caqueta                9        9          9
                                Huila                  3        3          3
                                Norte de Santander     1        1          1
                                Santander              1        1          1
                                Valle del Cauca        1        1          1
              De 15 a 19 años   Bogotá                 4        4          4
                                Nariño                 1        1          1
                                Quindio                1        1          1
              De 20 a 24 años   Huila                  1        1          1
                                Valle del Cauca        1        1          1
              De 25 a 29 años   Antioquia              1        1          1
              De 30 a 34 años   Amazonas               1        1          1
                                Arauca                 1        1          1
                                Nariño                 2        2          2
                                Valle del Cauca        1        1          1
              De 35 a 39 años   Nariño                 1        1          1
              De 40 a 44 años   Nariño                 2        2          2
                                Tolima                 1        1          1
              De 45 a 49 años   Bogotá                 1        1          1
                                Valle del Cauca        1        1          1
              De 5 a 9 años     Atlántico              1        1          1
                                Bogotá                 1        1          1
              De 50 a 54 años   Atlántico              1        1          1
                                Bogotá                 1        1          1
                                Cundinamarca           1        1          1
                                Putumayo               1        1          1
                                Quindio                1        1          1
                                Valle del Cauca        1        1          1
              De 55 a 59 años   Guaviare               1        1          1
                                Tolima                 1        1          1
              De 60 a 64 años   Atlántico              1        1          1
                                Bogotá                 1        1          1
                                Caldas                 1        1          1
              De 65 a 69 años   Antioquia              1        1          1
              De 70 a 74 años   Bogotá                 3        3          3
                                Caldas                 1        1          1
              De 75 a 79 años   Bogotá                 1        1          1
                                Valle del Cauca        1        1          1
              De 80 a 84 años   Atlántico              1        1          1
              De 90 a 94 años   Cauca                  1        1          1
                                Cundinamarca           1        1          1
              De 95 a 99 años   Antioquia              2        2          2
                                Cauca                  1        1          1
                                Huila                  1        1          1
                                Norte de Santander     1        1          1
              Edad desconocida  Arauca                 1        1          1
                                Boyaca                 1        1          1
                                Choco                  1        1          1
                                Cundinamarca           3        3          3
                                Nariño                 3        3          3
                                Quindio                2        2          2

                                                    GRU_ED2  NIVEL_EDU  \
SEXO          GRU_ED1           COD_DPTO
Femenino      Edad desconocida  Nariño                    1          1
Indeterminado De 0 a 4 años     Antioquia                 1          1
                                Atlántico                 1          1
                                Bogotá                    2          2
                                Santander                 1          1
                                Valle del Cauca           1          1
              De 100 años y más Bogotá                    1          1
                                Caqueta                   9          9
                                Huila                     3          3
                                Norte de Santander        1          1
                                Santander                 1          1
                                Valle del Cauca           1          1
              De 15 a 19 años   Bogotá                    4          4
                                Nariño                    1          1
                                Quindio                   1          1
              De 20 a 24 años   Huila                     1          1
                                Valle del Cauca           1          1
              De 25 a 29 años   Antioquia                 1          1
              De 30 a 34 años   Amazonas                  1          1
                                Arauca                    1          1
                                Nariño                    2          2
                                Valle del Cauca           1          1
              De 35 a 39 años   Nariño                    1          1
              De 40 a 44 años   Nariño                    2          2
                                Tolima                    1          1
              De 45 a 49 años   Bogotá                    1          1
                                Valle del Cauca           1          1
              De 5 a 9 años     Atlántico                 1          1
                                Bogotá                    1          1
              De 50 a 54 años   Atlántico                 1          1
                                Bogotá                    1          1
                                Cundinamarca              1          1

As there are only 82 people who have unknown sex or age, corresponding for each range and department 1 or 2 in general, there will be ommited for this purpose.

In [27]:
d18_2=d18[~((d18.GRU_ED1=='Edad desconocida') | (d18.SEXO=='Indeterminado'))]
d18_2.head()

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,ULTCURFAL,MUERTEPORO,SIMUERTEPO,OCUPACION,IDPERTET,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,IDADMISALUD,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,ULTCURMAD,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,C_MUERTEB,C_MUERTEC,C_MUERTED,C_MUERTEE,ASIS_MED,C_DIR1,C_DIR12,C_ANT1,C_ANT12,C_ANT2,C_ANT22,C_ANT3,C_ANT32,C_PAT1,C_PAT2,C_BAS1,C_MCM1,CAUSA_667,IDPROFCER,CAU_HOMOL,COD_DPTO2
0,Caldas,50,Cabecera municipal,Vía pública,,Defunción no fetal,2018,Enero,15,5,Masculino,Estaba casado(a),De 50 a 54 años,De 45 a 64 años,Profesional,5,2,,CONTADORES,Ninguno de las anteriores,Colombia,Caldas,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R570,,I219,,,,,,,,I219,,303,1,51,17
1,Caqueta,592,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,8,15,Masculino,Estaba viudo(a),De 85 a 89 años,De 65 y mas años,Básica primaria,5,2,,AGRICULTORES DE CULTIVOS TRANSITORIOS,Ninguno de las anteriores,Colombia,Caqueta,592,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,R570,,R688,,E43,,,,R011,,E43,,602,1,42,18
2,Caldas,13,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,10,0,Femenino,Estaba viudo(a),De 95 a 99 años,De 65 y mas años,Ninguno,0,2,,COCINEROS Y AFINES,Ninguno de las anteriores,Colombia,Caldas,13,Cabecera municipal,Subsidiado,2,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,,,1,,No,I219,,,,,,,,I10,E785,I219,,303,1,51,17
3,Antioquia,1,Cabecera municipal,Casa /domicilio,,Defunción no fetal,2018,Enero,12,15,Masculino,Estaba casado(a),De 80 a 84 años,De 65 y mas años,Básica primaria,5,2,,PENSIONADO,Ninguno de las anteriores,Colombia,Antioquia,1,Cabecera municipal,Contributivo,1,Natural,Médico no tratante,,,,,,,,,,,0,,,,,,,,1,,1,,Sí,R090,,C20,,,,,,,,C20,,203,1,14,5
4,Meta,1,Cabecera municipal,Hospital/clínica,,Defunción no fetal,2018,Enero,11,0,Femenino,No estaba casado(a) y llevaba dos o más años v...,De 85 a 89 años,De 65 y mas años,Básica primaria,3,2,,HOGAR,Ninguno de las anteriores,Colombia,Meta,226,Cabecera municipal,Subsidiado,2,Natural,Médico tratante,,,,,,,,,,,0,,,,,,,,1,1,,,Sí,K650,,K658,,K358,K388,,,I119,,K352,,607,1,65,50

In [28]:
d18_2=d18_2.groupby(['COD_DPTO2','SEXO','GRU_ED1']).agg({'A_DEFUN':'count'}).reset_index().rename(columns={'A_DEFUN':'Número'})

In [29]:
diclist=zip([[int(s) for s in str.split(a) if s.isdigit()][0] for a in d18_2.GRU_ED1.unique()],d18_2.GRU_ED1.unique().tolist())
dic_edad={x: y for y, x in diclist }
dic_edad

{'De 0 a 4 años': 0,
 'De 10 a 14 años': 10,
 'De 100 años y más': 100,
 'De 15 a 19 años': 15,
 'De 20 a 24 años': 20,
 'De 25 a 29 años': 25,
 'De 30 a 34 años': 30,
 'De 35 a 39 años': 35,
 'De 40 a 44 años': 40,
 'De 45 a 49 años': 45,
 'De 5 a 9 años': 5,
 'De 50 a 54 años': 50,
 'De 55 a 59 años': 55,
 'De 60 a 64 años': 60,
 'De 65 a 69 años': 65,
 'De 70 a 74 años': 70,
 'De 75 a 79 años': 75,
 'De 80 a 84 años': 80,
 'De 85 a 89 años': 85,
 'De 90 a 94 años': 90,
 'De 95 a 99 años': 95}

In [30]:
diclist=zip([int(re.findall(r'\d+', a)[0]) for a in  df18_3.RangoEdad.unique().tolist()],
            df18_3.RangoEdad.unique().tolist() )
dic_edad2={x: y for y, x in diclist }
dic_edad2

{'[0.0, 5.0)': 0,
 '[10.0, 15.0)': 10,
 '[100.0, 105.0)': 100,
 '[15.0, 20.0)': 15,
 '[20.0, 25.0)': 20,
 '[25.0, 30.0)': 25,
 '[30.0, 35.0)': 30,
 '[35.0, 40.0)': 35,
 '[40.0, 45.0)': 40,
 '[45.0, 50.0)': 45,
 '[5.0, 10.0)': 5,
 '[50.0, 55.0)': 50,
 '[55.0, 60.0)': 55,
 '[60.0, 65.0)': 60,
 '[65.0, 70.0)': 65,
 '[70.0, 75.0)': 70,
 '[75.0, 80.0)': 75,
 '[80.0, 85.0)': 80,
 '[85.0, 90.0)': 85,
 '[90.0, 95.0)': 90,
 '[95.0, 100.0)': 95}

In [31]:
df18_3['Rango2']=df18_3.RangoEdad.map(dic_edad2)
df18_3=df18_3[['DP','Sexo','Rango2','Número']]
df18_3

      DP     Sexo  Rango2  Número
0      5  Hombres       0  460982
1      5  Hombres      10  493364
2      5  Hombres     100    2386
3      5  Hombres      15  535660
4      5  Hombres      20  569772
...   ..      ...     ...     ...
1381  99  Mujeres      75     452
1382  99  Mujeres      80     264
1383  99  Mujeres      85     138
1384  99  Mujeres      90      64
1385  99  Mujeres      95      34

[1386 rows x 4 columns]

In [32]:
d18_2['Rango2']=d18_2.GRU_ED1.map(dic_edad)
d18_2=d18_2.rename(columns={'Número':'Muertes','COD_DPTO2':'DPTO'})[['DPTO','SEXO','Rango2','Muertes']]
d18_2

      DPTO       SEXO  Rango2  Muertes
0        5   Femenino       0      374
1        5   Femenino      10       57
2        5   Femenino     100      180
3        5   Femenino      15      110
4        5   Femenino      20      154
...    ...        ...     ...      ...
1345    99  Masculino      70        8
1346    99  Masculino      75       14
1347    99  Masculino      80        7
1348    99  Masculino      85        4
1349    99  Masculino      90        3

[1350 rows x 4 columns]

## Natality 2018 adjustments

In [33]:
n18.head()

,COD_DPTO,COD_MUNIC,AREANAC,SIT_PARTO,OTRO_SIT,SEXO,PESO_NAC,TALLA_NAC,ANO,MES,ATEN_PAR,T_GES,NUMCONSUL,TIPO_PARTO,MUL_PARTO,APGAR1,APGAR2,IDHEMOCLAS,IDFACTORRH,IDPERTET,EDAD_MADRE,EST_CIVM,NIV_EDUM,ULTCURMAD,CODPRES,CODPTORE,CODMUNRE,AREA_RES,N_HIJOSV,FECHA_NACM,N_EMB,SEG_SOCIAL,IDCLASADMI,EDAD_PADRE,NIV_EDUP,ULTCURPAD,PROFESION
0,5,1,1,1,,1,7,5,2018,1,1,4,8,1,1,8,10,1,1,6,4,1,4,11,170,27,1,1,2,13/08/2014,2,1,1,30,4,11,1
1,11,1,1,1,,1,6,5,2018,1,1,4,9,1,1,9,10,1,1,6,5,6,9,5,170,11,1,1,1,,1,1,1,36,9,5,1
2,52,1,1,1,,1,6,5,2018,1,1,3,11,2,1,7,10,4,1,6,4,1,5,11,170,52,885,1,2,15/02/2011,3,2,2,27,4,11,1
3,11,1,1,1,,1,6,5,2018,1,1,4,8,2,1,8,9,3,1,6,5,1,9,5,170,11,1,1,1,,2,1,1,32,9,5,1
4,50,1,1,1,,1,5,4,2018,1,1,4,8,2,1,8,9,3,1,6,3,2,9,4,170,50,6,3,1,,1,2,2,21,4,11,1

In [34]:
n18_2=n18[['COD_DPTO','SEXO']].copy()
n18_2['Rango2']=0
n18_2['Nacimientos']=1
n18_2.isna().sum()

COD_DPTO       0
SEXO           0
Rango2         0
Nacimientos    0
dtype: int64

In [35]:
print(n18_2.COD_DPTO.unique(),"\n",n18_2.SEXO.unique())

[ 5 11 52 50 18 70 86 54 20 68 76  8 13 25 44 23 19 73 41 63 66 15 17 27
 47 81 85 91 99 95 97 88 94]
 [1 2 3]

In [36]:
#3 indeterminado
n18_2[n18_2.SEXO==3].groupby(['COD_DPTO','SEXO','Rango2']).count()

                      Nacimientos
COD_DPTO SEXO Rango2
5        3    0                 6
8        3    0                 3
11       3    0                 8
13       3    0                11
17       3    0                 1
19       3    0                 2
23       3    0                 4
25       3    0                 3
27       3    0                 1
41       3    0                 1
44       3    0                 6
47       3    0                 4
50       3    0                 2
52       3    0                 4
68       3    0                 4
76       3    0                 9
81       3    0                 1
91       3    0                 1
97       3    0                 1

As there are few births with undetermined sex by department, for this analysis they won't be taken into account.

In [37]:
n18_2=n18_2[n18_2.SEXO!=3]
dicsex={1:'Masculino',2:'Femenino'}
n18_2.SEXO=n18_2.SEXO.map(dicsex)

In [38]:
n18_2=n18_2.groupby(['COD_DPTO','SEXO','Rango2']).agg({'Nacimientos':'sum'}).reset_index()
n18_2

    COD_DPTO       SEXO  Rango2  Nacimientos
0          5   Femenino       0        36321
1          5  Masculino       0        38177
2          8   Femenino       0        21383
3          8  Masculino       0        22414
4         11   Femenino       0        50597
..       ...        ...     ...          ...
61        95  Masculino       0          671
62        97   Femenino       0          327
63        97  Masculino       0          339
64        99   Femenino       0          555
65        99  Masculino       0          573

[66 rows x 4 columns]

## 2017 estimate

In [39]:
dictsex={'Hombres':'Masculino','Mujeres':'Femenino'}
df18_3=df18_3.assign(Sexo = lambda x: x.Sexo.map(dictsex))
df18_3

      DP       Sexo  Rango2  Número
0      5  Masculino       0  460982
1      5  Masculino      10  493364
2      5  Masculino     100    2386
3      5  Masculino      15  535660
4      5  Masculino      20  569772
...   ..        ...     ...     ...
1381  99   Femenino      75     452
1382  99   Femenino      80     264
1383  99   Femenino      85     138
1384  99   Femenino      90      64
1385  99   Femenino      95      34

[1386 rows x 4 columns]

In [40]:
df18_3.isna().sum()

DP        0
Sexo      0
Rango2    0
Número    0
dtype: int64

In [41]:
#merge
df18_3=df18_3.rename(columns={'Sexo':'SEXO','DP':'DPTO'})
n18_2=n18_2.rename(columns={'COD_DPTO':'DPTO'})
df17=df18_3.merge(d18_2,how='outer').merge(n18_2, how='outer')
df17

      DPTO       SEXO  Rango2  Número  Muertes  Nacimientos
0        5  Masculino       0  460982    423.0      38177.0
1        5  Masculino      10  493364    104.0          NaN
2        5  Masculino     100    2386     80.0          NaN
3        5  Masculino      15  535660    479.0          NaN
4        5  Masculino      20  569772    842.0          NaN
...    ...        ...     ...     ...      ...          ...
1381    99   Femenino      75     452      5.0          NaN
1382    99   Femenino      80     264      6.0          NaN
1383    99   Femenino      85     138      2.0          NaN
1384    99   Femenino      90      64      3.0          NaN
1385    99   Femenino      95      34      2.0          NaN

[1386 rows x 6 columns]

In [42]:
df17.isna().sum()

DPTO              0
SEXO              0
Rango2            0
Número            0
Muertes          36
Nacimientos    1320
dtype: int64

In [43]:
df17.fillna(0,inplace=True)
df17['Poblacion1']=df17.Número - df17.Muertes + df17.Nacimientos
df17['Prop escala']=round(df17['Número']*1/5)
df17=df17.sort_values(by='Rango2', ascending=False).reset_index().drop(columns='index')
df17

,DPTO,SEXO,Rango2,Número,Muertes,Nacimientos,Poblacion1,Prop escala
0,54,Femenino,100,590,26.0,0.0,564.0,118.0
1,23,Femenino,100,1060,32.0,0.0,1028.0,212.0
2,66,Masculino,100,430,16.0,0.0,414.0,86.0
3,23,Masculino,100,758,28.0,0.0,730.0,152.0
4,66,Femenino,100,680,21.0,0.0,659.0,136.0
...,...,...,...,...,...,...,...,...
1381,63,Femenino,0,31018,26.0,2879.0,33871.0,6204.0
1382,63,Masculino,0,32596,47.0,3008.0,35557.0,6519.0
1383,54,Femenino,0,124388,126.0,11420.0,135682.0,24878.0
1384,54,Masculino,0,130600,188.0,12011.0,142423.0,26120.0
1385,52,Femenino,0,124482,101.0,8893.0,133274.0,24896.0

In [44]:
df17['Cambio']=df17[['DPTO','SEXO','Prop escala']].groupby(['DPTO','SEXO']).shift().fillna(0)
df17['Poblacion']=df17.Número + df17.Muertes - df17.Nacimientos-df17['Prop escala']+df17.Cambio
df17

,DPTO,SEXO,Rango2,Número,Muertes,Nacimientos,Poblacion1,Prop escala,Cambio,Poblacion
0,54,Femenino,100,590,26.0,0.0,564.0,118.0,0.0,498.0
1,23,Femenino,100,1060,32.0,0.0,1028.0,212.0,0.0,880.0
2,66,Masculino,100,430,16.0,0.0,414.0,86.0,0.0,360.0
3,23,Masculino,100,758,28.0,0.0,730.0,152.0,0.0,634.0
4,66,Femenino,100,680,21.0,0.0,659.0,136.0,0.0,565.0
...,...,...,...,...,...,...,...,...,...,...
1381,63,Femenino,0,31018,26.0,2879.0,33871.0,6204.0,6215.0,28176.0
1382,63,Masculino,0,32596,47.0,3008.0,35557.0,6519.0,6570.0,29686.0
1383,54,Femenino,0,124388,126.0,11420.0,135682.0,24878.0,24647.0,112863.0
1384,54,Masculino,0,130600,188.0,12011.0,142423.0,26120.0,26072.0,118729.0
1385,52,Femenino,0,124482,101.0,8893.0,133274.0,24896.0,24681.0,115475.0

In [45]:
diclist=zip([int(re.findall(r'\d+', a)[0]) for a in  dic_edad.keys()],dic_edad.keys() )
dic_edad2={x: y for x, y in diclist }
dic_edad2

{0: 'De 0 a 4 años',
 10: 'De 10 a 14 años',
 100: 'De 100 años y más',
 15: 'De 15 a 19 años',
 20: 'De 20 a 24 años',
 25: 'De 25 a 29 años',
 30: 'De 30 a 34 años',
 35: 'De 35 a 39 años',
 40: 'De 40 a 44 años',
 45: 'De 45 a 49 años',
 5: 'De 5 a 9 años',
 50: 'De 50 a 54 años',
 55: 'De 55 a 59 años',
 60: 'De 60 a 64 años',
 65: 'De 65 a 69 años',
 70: 'De 70 a 74 años',
 75: 'De 75 a 79 años',
 80: 'De 80 a 84 años',
 85: 'De 85 a 89 años',
 90: 'De 90 a 94 años',
 95: 'De 95 a 99 años'}

In [46]:
df18_4=df18_3.rename(columns={'Número':'POBLACION','Rango2':'RANGOEDAD'})
df18_4['AÑO']=2018
df18_4

      DPTO       SEXO  RANGOEDAD  POBLACION   AÑO
0        5  Masculino          0     460982  2018
1        5  Masculino         10     493364  2018
2        5  Masculino        100       2386  2018
3        5  Masculino         15     535660  2018
4        5  Masculino         20     569772  2018
...    ...        ...        ...        ...   ...
1381    99   Femenino         75        452  2018
1382    99   Femenino         80        264  2018
1383    99   Femenino         85        138  2018
1384    99   Femenino         90         64  2018
1385    99   Femenino         95         34  2018

[1386 rows x 5 columns]

In [47]:
df17_2=df17[['DPTO','SEXO','Rango2','Poblacion']].rename(columns={'Poblacion':'POBLACION','Rango2':'RANGOEDAD'})
df17_2['AÑO']=2017
df17_2

      DPTO       SEXO  RANGOEDAD  POBLACION   AÑO
0       54   Femenino        100      498.0  2017
1       23   Femenino        100      880.0  2017
2       66  Masculino        100      360.0  2017
3       23  Masculino        100      634.0  2017
4       66   Femenino        100      565.0  2017
...    ...        ...        ...        ...   ...
1381    63   Femenino          0    28176.0  2017
1382    63  Masculino          0    29686.0  2017
1383    54   Femenino          0   112863.0  2017
1384    54  Masculino          0   118729.0  2017
1385    52   Femenino          0   115475.0  2017

[1386 rows x 5 columns]

In [48]:
dffinal=df17_2.append(df18_4)
dffinal

      DPTO       SEXO  RANGOEDAD  POBLACION   AÑO
0       54   Femenino        100      498.0  2017
1       23   Femenino        100      880.0  2017
2       66  Masculino        100      360.0  2017
3       23  Masculino        100      634.0  2017
4       66   Femenino        100      565.0  2017
...    ...        ...        ...        ...   ...
1381    99   Femenino         75      452.0  2018
1382    99   Femenino         80      264.0  2018
1383    99   Femenino         85      138.0  2018
1384    99   Femenino         90       64.0  2018
1385    99   Femenino         95       34.0  2018

[2772 rows x 5 columns]

In [49]:
Deptos={ 5: 'Antioquia', 8: 'Atlántico', 11: 'Bogotá', 13: 'Bolivar', 15: 'Boyaca', 17: 'Caldas', 18: 'Caqueta', 19: 'Cauca', 20: 'Cesar', 23: 'Cordoba', 25: 'Cundinamarca', 27: 'Choco', 41: 'Huila', 44: 'La guajira', 47: 'Magdalena', 50: 'Meta', 52: 'Nariño', 54: 'Norte de Santander', 63: 'Quindio', 66: 'Risaralda', 68: 'Santander', 70: 'Sucre', 73: 'Tolima', 76: 'Valle del Cauca', 81: 'Arauca', 85: 'Casanare', 86: 'Putumayo', 88: 'San Andrés y Providencia', 91: 'Amazonas', 94: 'Guainía', 95: 'Guaviare', 97: 'Vaupés', 99: 'Vichada'}
dffinal['RANGOEDAD']=dffinal.RANGOEDAD.map(dic_edad2)
dffinal['DPTO']=dffinal['DPTO'].map(Deptos)
dffinal

                    DPTO       SEXO          RANGOEDAD  POBLACION   AÑO
0     Norte de Santander   Femenino  De 100 años y más      498.0  2017
1                Cordoba   Femenino  De 100 años y más      880.0  2017
2              Risaralda  Masculino  De 100 años y más      360.0  2017
3                Cordoba  Masculino  De 100 años y más      634.0  2017
4              Risaralda   Femenino  De 100 años y más      565.0  2017
...                  ...        ...                ...        ...   ...
1381             Vichada   Femenino    De 75 a 79 años      452.0  2018
1382             Vichada   Femenino    De 80 a 84 años      264.0  2018
1383             Vichada   Femenino    De 85 a 89 años      138.0  2018
1384             Vichada   Femenino    De 90 a 94 años       64.0  2018
1385             Vichada   Femenino    De 95 a 99 años       34.0  2018

[2772 rows x 5 columns]

In [50]:
dffinal.columns=['DEPARTAMENTO', 'SEXO', 'RANGOEDAD', 'POBLACION', 'AÑO']
dffinal=dffinal[['DEPARTAMENTO', 'AÑO', 'RANGOEDAD', 'SEXO', 'POBLACION']]
dffinal

            DEPARTAMENTO   AÑO          RANGOEDAD       SEXO  POBLACION
0     Norte de Santander  2017  De 100 años y más   Femenino      498.0
1                Cordoba  2017  De 100 años y más   Femenino      880.0
2              Risaralda  2017  De 100 años y más  Masculino      360.0
3                Cordoba  2017  De 100 años y más  Masculino      634.0
4              Risaralda  2017  De 100 años y más   Femenino      565.0
...                  ...   ...                ...        ...        ...
1381             Vichada  2018    De 75 a 79 años   Femenino      452.0
1382             Vichada  2018    De 80 a 84 años   Femenino      264.0
1383             Vichada  2018    De 85 a 89 años   Femenino      138.0
1384             Vichada  2018    De 90 a 94 años   Femenino       64.0
1385             Vichada  2018    De 95 a 99 años   Femenino       34.0

[2772 rows x 5 columns]

In [51]:
dffinal.dtypes

DEPARTAMENTO     object
AÑO               int64
RANGOEDAD        object
SEXO             object
POBLACION       float64
dtype: object

In [52]:
dffinal.DEPARTAMENTO=dffinal.DEPARTAMENTO.astype('category')
dffinal.AÑO=dffinal.AÑO.astype('int16')
dffinal.RANGOEDAD=dffinal.RANGOEDAD.astype('category')
dffinal.SEXO=dffinal.SEXO.astype('category')
dffinal.POBLACION=dffinal.POBLACION.astype('int64')

In [53]:
dffinal.to_parquet('../parquet_datasets/Poblacion2017_2018.parquet')